export const SIGN_IN_WITH_GOOGLE = "app/SignIn/SIGN_IN_WITH_GOOGLE";
export const SIGN_IN_WITH_GOOGLE_SUCCESS =
  "app/SignIn/SIGN_IN_WITH_GOOGLE_SUCCESS";
export const SIGN_IN_WITH_GOOGLE_FAILED =
  "app/SignIn/SIGN_IN_WITH_GOOGLE_FAILED";

export const SIGN_IN_WITH_FACEBOOK = "app/SignIn/SIGN_IN_WITH_FACEBOOK";
export const SIGN_IN_WITH_FACEBOOK_SUCCESS =
  "app/SignIn/SIGN_IN_WITH_FACEBOOK_SUCCESS";
export const SIGN_IN_WITH_FACEBOOK_FAILED =
  "app/SignIn/SIGN_IN_WITH_FACEBOOK_FAILED";
