export const SIGN_IN = "app/SignIn/SIGN_IN";
export const SIGN_IN_SUCCESS = "app/SignIn/SIGN_IN_SUCCESS";
export const SIGN_IN_FAILED = "app/SignIn/SIGN_IN_FAILED";

export const SIGN_IN_WITH_GOOGLE = "app/SignIn/SIGN_IN_WITH_GOOGLE";
export const SIGN_IN_WITH_GOOGLE_SUCCESS =
  "app/SignIn/SIGN_IN_WITH_GOOGLE_SUCCESS";
export const SIGN_IN_WITH_GOOGLE_FAILED =
  "app/SignIn/SIGN_IN_WITH_GOOGLE_FAILED";

export const SIGN_IN_WITH_FACEBOOK = "app/SignIn/SIGN_IN_WITH_FACEBOOK";
export const SIGN_IN_WITH_FACEBOOK_SUCCESS =
  "app/SignIn/SIGN_IN_WITH_FACEBOOK_SUCCESS";
export const SIGN_IN_WITH_FACEBOOK_FAILED =
  "app/SignIn/SIGN_IN_WITH_FACEBOOK_FAILED";

export const SIGN_IN_WITH_TWITTER = "app/SignIn/SIGN_IN_WITH_TWITTER";
export const SIGN_IN_WITH_TWITTER_SUCCESS =
  "app/SignIn/SIGN_IN_WITH_TWITTER_SUCCESS";
export const SIGN_IN_WITH_TWITTER_FAILED =
  "app/SignIn/SIGN_IN_WITH_TWITTER_FAILED";
